# global settings file
---
  # show only the <N> most recent ads during a scrape. 0 to alwats show all ads
  recent_ads: 3

  # total log files to keep in rotation
  log_rotation_files: 1

  # a global include list so you dont have to set it for every task
  # global_include:
  # a global exclude list so you dont have to set it for every task
  # global_exclude:
